"""
generator_c.py - Family C: Generación parcial (boot + seed parametric split).

Strategy:
  - Determine the minimum boot code that induces D to walk DATA region
  - Replace rest of code with minimal construction
  - DATA region stores compressed seed that boot code expands
"""

import hashlib
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..'))

ENCRYPT = "5z]&gqtyfr$(we4{WP)H-Zn,[%\\3dL+Q;>U!pJS72FhOA1CB6v^=I_0/8|jsb9m<.TVac`uY*MK'X~xDl}REokN:#?G\"i@"
CRAZY_TBL = [[1, 0, 0], [1, 0, 2], [2, 2, 1]]
POW10 = 59049


def crazy(a, b):
    res, p = 0, 1
    for _ in range(10):
        res += CRAZY_TBL[b % 3][a % 3] * p
        a, b, p = a // 3, b // 3, p * 3
    return res


def rotate(n):
    return (n % 3) * 19683 + (n // 3)


def load_baseline_clean():
    with open('quine_research/baseline_quine.mal', 'r', encoding='latin1') as f:
        raw = f.read()
    clean = ''.join(c for c in raw if 33 <= ord(c) <= 126)
    return raw, clean


def make_raw_preserving_structure(clean_source, new_clean):
    raw_base, _ = load_baseline_clean()
    assert len(new_clean) == len(clean_source)
    new_raw = []
    ci = 0
    for ch in raw_base:
        if 33 <= ord(ch) <= 126:
            new_raw.append(new_clean[ci])
            ci += 1
        else:
            new_raw.append(ch)
    return ''.join(new_raw)


def analyze_baseline_structure():
    """Determina donde termina el boot code y donde empieza la DATA region."""
    raw, clean = load_baseline_clean()
    code = clean[:29516]
    data = clean[29516:59032]
    
    # Find where the main loop starts: look for repeated 'jmp' patterns
    # that read from D pointers starting at 29516
    # Heuristic: find first char position where D-read frequency is high
    
    # Find boot section: early chars that participate in mov_d chain
    # (positions where the baseline sets d=29516)
    boot_end = 0
    
    # Try to find first 'x' or 'J' which appears at PC 29200 (main loop body)
    # Actually, better: the boot code SHOULD BE everything BEFORE the first
    # character-output instruction at pc ~28000.
    
    # Heuristic: split at position of first 'out' opcode in the structural trace
    # From baseline_analysis: first out at pc 29356
    # So boot is roughly 29356 bytes... but that's almost everything.
    # Actually in the baseline the "boot" is the bootstrapping sequence that
    # sets d=29516 via mov_d, then falls into the main print loop.
    
    # Let's look for the 'jmp' + 'mov_d' pairs that form the fast-forward chain
    # In the baseline these occur early (in the first 100 bytes)
    
    return code, data


def generate_c_boot_fastforward_repeat(boot_size, repeat_seed):
    """
    Family C: Boot code of boot_size bytes, then boot code is REPEATED in the CODE region
    DATA region contains a compressed seed that regenerates repeat_seed on the fly.
    
    Concept: The code region IS the boot (short), and output is generated by:
    1. Running boot that sets up loop
    2. Loop reads from DATA (seed) and prints using crazy/rotr transforms
    3. DATA is compressed seed, repeated pattern
    
    boot_size: bytes in boot code (must be enough to establish jump chain)
    """
    raw_base, clean_base = load_baseline_clean()
    code_region = clean_base[:29516]
    data_region = clean_base[29516:59032]
    
    # Boot = first boot_size bytes of code_region
    # Pad code_region to 29516 by repeating boot
    repeated_boot = (code_region[:boot_size] * (29516 // boot_size + 1))[:29516]
    
    # DATA = repeat_seed repeated to fill 29516
    seed = data_region[:repeat_seed]
    repeated_data = (seed * (29516 // repeat_seed + 1))[:29516]
    
    new_clean = repeated_boot + repeated_data
    new_raw = make_raw_preserving_structure(clean_base, new_clean)
    
    return {
        'family': 'C',
        'params': {'boot_size': boot_size, 'repeat_seed': repeat_seed},
        'code': repeated_boot,
        'data': repeated_data,
        'raw': new_raw,
        'source_size': len(new_raw),
        'code_size': len(repeated_boot),
        'data_size': len(repeated_data),
        'note': f'Boot {boot_size}B + repeated DATA seed {repeat_seed}B',
    }


def generate_c_alternating_pass():
    """
    Family C: Two-pass interleaved output where only ONE pass is stored in DATA.
    The other pass is generated by a simple transformation at runtime.
    
    E.g., assume DATA = chr((ord(x) + 1) % 94 + 33), and bootcode adds rotr before out.
    """
    raw_base, clean_base = load_baseline_clean()
    code_region = clean_base[:29516]
    data_region = clean_base[29516:59032]
    
    # Try offset=13: DATA[i] = rotate(code[i])
    transformed_data = ''.join(chr((rotate(ord(data_region[i])) % 94) + 33) for i in range(len(data_region)))
    
    new_clean = code_region + transformed_data
    new_raw = make_raw_preserving_structure(clean_base, new_clean)
    
    return {
        'family': 'C',
        'params': {'method': 'rotr_data'},
        'code': code_region,
        'data': transformed_data,
        'raw': new_raw,
        'source_size': len(new_raw),
        'code_size': len(code_region),
        'data_size': len(transformed_data),
        'note': 'DATA = rotr(original_DATA) - competing variant of B1_off',
    }


def generate_all_family_c():
    candidates = []
    
    # C1: boot + repeat, various boot sizes
    for boot_size in [100, 300, 500, 1000, 2000, 5000]:
        for repeat_seed in [512, 1024, 2048, 4096, 8192]:
            candidates.append(generate_c_boot_fastforward_repeat(boot_size, repeat_seed))
    
    # C2: alternating (transformed DATA, requires modified boot)
    candidates.append(generate_c_alternating_pass())
    
    return candidates


if __name__ == '__main__':
    import json
    candidates = generate_all_family_c()
    os.makedirs('quine_research/generated', exist_ok=True)
    for c in candidates[:3]:  # первые 3
        cid = f'C_{hash(str(c[\"params\"])) % 10000}'
        path = f'quine_research/generated/C_{cid}.mal'
        with open(path, 'w', encoding='latin1') as f:
            f.write(c['raw'])
        print(f'  Generated C_{cid}: size={c[\"source_size\"]} boot={c[\"params\"][\"boot_size\"]}B')
    
    print(f'\nTotal C candidates generated: {len(candidates)}')